### ISSUE TITLE
Running scala tests via sbt doesn't work

### ISSUE THREAD

**Issue by baltazarortiz** [ucb-bar/gemmini#10]
I tried running the PipelineTest with `sbt 'testOnly gemmini.PipelineUnitTest'` and got a pile of errors that as far as I could tell came down to Scala not being able to find `hardfloat` or `freechips`. Is there a way to run the tests?

**Comment by HaFred** [comment]
According to the author, the chisel tests under the repo `src/test` are out-dated. Not recommended for usage.
