### ISSUE TITLE
a possible description error in Readme file

### ISSUE THREAD

**Issue by Lyon-ai** [ucb-bar/gemmini#139]
Hello，
ps: It is only a small issue, not making influence on implementation of Gemmini.

I think the action description on **mvout**, which is **Action: DRAM[Translate[rs2]] <= Scratchpad[rs1]** , should exchange the position of r1 and r2, changing into **Action: DRAM[Translate[rs1]] <= Scratchpad[rs2]**
By definition, r1 is the virtual DRAM address, and r2 is the S_pad address. 
And according to the test example in mvin_mvout.c:

 for (size_t n = 0; n < N; ++n) {
    // printf("Mvin %d\n", n);
    gemmini_mvin(In[n], n*DIM);
    // printf("Mvout %d\n", n);
    gemmini_mvout(Out[n], n*DIM);
  }

We store the information of In matrix into sp[n*DIM] rather than sp[Out[n]]

**Comment by hngenc** [comment]
You are correct, and I've just fixed this in `dev`. Thank you for catching this!
