### ISSUE TITLE
ExecuteController code question

### ISSUE THREAD

**Issue by thuako** [ucb-bar/gemmini#141]
In ExecuteController.scala there is multiple wiring to start_inputting_b without mux.

```
elsewhen(DoComputes(0)) {
          perform_single_mul := true.B
          performing_single_mul := true.B

          start_inputting_a := !a_should_be_fed_into_transposer
          start_inputting_b := !b_should_be_fed_into_transposer
          start_inputting_b := true.B

          control_state := compute
        }
```

I don't understand why this code works.

Is there anybody to explain this code?

**Comment by hngenc** [comment]
Thanks for catching that, that must be a typo. One of those two `start_inputting_b` lines can be deleted. I'll look into this to see which one we can get rid of.
