### ISSUE TITLE
gemini-rocc-tests env config

### ISSUE THREAD

**Issue by xiaolingyi** [ucb-bar/gemmini#15]
Hi,i am a newb at this project,and when i try to run ./build.sh under the gemmini-rocc-tests directory,i encounter the error that  "make[1]:riscv64-unknown-elf-gcc":Command not found.
So,i think that i might need to config the dependency.So ,what should i install before i run ./build.sh?
Thanks a lot!y

**Comment by hngenc** [comment]
Did you remember to run `./scripts/build-toolchains.sh esp-tools`, as described in the link below?

https://chipyard.readthedocs.io/en/latest/

After running that, you should run `source ./env.sh` before running `./build.sh`
