### ISSUE TITLE
Customizing PE, Tile, Mesh

### ISSUE THREAD

**Issue by jaeyonglee0205** [ucb-bar/gemmini#157]
Hi, thanks for the great work.

I'm currently trying to implement my own customization in PE.scala, Tile.scala, and Mesh.scala in src/main, however I don't really see a connection between those scala files and gemmini codes, except for customizing parameters in gemmini_params.h.

Say, that I successfully implemented new features. If I `make CONFIG=GemminiRocketConfig`, does this change the files in gemmini-rocc-tests/include (just like changing the parameters meshRow and meshColumn) and gemmini.cc in spike? Or should I also customize the functions in them?

**Comment by hngenc** [comment]
What kinds of customizations are you thinking of implementing?

If you change the source code and rebuild `CONFIG=GemminiRocketConfig`, then it probably won't change `gemmini_params.h` unless you also change `GemminiConfigs.scala`. `GemminiConfigs.scala` is where `gemmini_params.h` is actually generated.
