### ISSUE TITLE
why the output of the tiled_ matmul_ nn_ auto() function is always 0?

### ISSUE THREAD

**Issue by Cuicunhao** [ucb-bar/gemmini#179]
I use the python generator script generates matmul, but the output of the tiled_ matmul_ nn_ auto() function is always 0,

I set parameter.h as follows:
elem_t input_mat[3][3] row_align(1)= {{1,1,1},{1,1,1},{1,1,1}};
elem_t weights0[3][3] row_align(1)= {{1,1,1},{1,1,1},{1,1,1}};
elem_t inter_results0[3][3] row_align(1)= {{1,1,1},{1,1,1},{1,1,1}};
elem_t weights1[3][3] row_align(1)= {{1,1,1},{1,1,1},{1,1,1}};
elem_t inter_results1[3][3] row_align(1)= {{1,1,1},{1,1,1},{1,1,1}};
//elem_t weights2[32][64] row_align(1)= {0};
//elem_t inter_results2[16][64] row_align(1)= {0};
//elem_t weights3[64][16] row_align(1)= {0};
//elem_t inter_results3[16][16] row_align(1)= {0};

and test.c like this:

printf("result00: %d\n",inter_results0[0][0]);
    /* matmul number: 0 */
    start = read_cycles();

    tiled_matmul_nn_auto(3, 3, 3,
        input_mat, weights0, NULL, inter_results0,
        RELU, 0, 0, false,
        tiled_matmul_type, check, "layer_0");

    end = read_cycles();
    cycles[0] = end-start;

    /* matmul number: 1 */
    start = read_cycles();

    tiled_matmul_nn_auto(3, 3, 3,
        inter_results0, weights1, NULL, inter_results1,
        RELU, 0, 0, false,
        tiled_matmul_type, check, "layer_1");

    end = read_cycles();
    cycles[1] = end-start;

  
    uint64_t overall_cycles = 0;
    for(int cyc = 0; cyc < 2 ; cyc++){
        overall_cycles += cycles[cyc];
        printf("Cycles taken in layer %d: %llu\n", cyc,cycles[cyc]);
    }
    printf("Overall cycles taken: %llu\n",overall_cycles);
printf("weight: %x\n",weights1[0][0]);
printf("result10: %d\n",inter_results1[0][0]);
    return 0;
}

the result is :
Gemmini extension configured with:
    dim = 16
input_mat
input_mat[0][0]: 1
input_mat[0][1]: 1
input_mat[0][2]: 1
input_mat[1][0]: 1
input_mat[1][1]: 1
input_mat[1][2]: 1
input_mat[2][0]: 1
input_mat[2][1]: 1
input_mat[2][2]: 1
weights0
weights0[0][0]: 1
weights0[0][1]: 1
weights0[0][2]: 1
weights0[1][0]: 1
weights0[1][1]: 1
weights0[1][2]: 1
weights0[2][0]: 1
weights0[2][1]: 1
weights0[2][2]: 1
before run the tiled_matmul_nn_auto the  inter_results0:
result[0][0]: 1
result[0][1]: 1
result[0][2]: 1
result[1][0]: 1
result[1][1]: 1
result[1][2]: 1
result[2][0]: 1
result[2][1]: 1
result[2][2]: 1
after run the tiled_matmul_nn_auto the  inter_results0:
result[0][0]: 0
result[0][1]: 0
result[0][2]: 0
result[1][0]: 0
result[1][1]: 0
result[1][2]: 0
result[2][0]: 0
result[2][1]: 0
result[2][2]: 0
I want to know why this happened. Thank you very much！

**Comment by hngenc** [comment]
Just wanted to check: were you able to figure out what the error was? If not, I can take a stab at it.
