### ISSUE TITLE
matrix_add only works for matrices with the same "DIM" 

### ISSUE THREAD

**Issue by johnny-wang16** [ucb-bar/gemmini#181]
Ideally, a matrix-adding function should work for matrices with arbitrary dimensions (or at least square matrices with arbitrary dimensions). The current method for adding matrices in  `matrix_add.c` only works when input matrices has the same dimension as the PE elements (indicated by the variable `DIM`). Under the default setting, the input matrices to the matrix-add function has to be 16x16 and dimensions other than this produces wrong output. I'm wondering if there's an easy way to add matrices with dimensions greater/smaller than the dimension of PE elements.

**Comment by hngenc** [comment]
Would the `tiled_resadd_auto` function work for you? You can see an example of it in `resadd.c`. It should be able to add two arbitrarily-sized matrices.

**Comment by johnny-wang16** [comment]
thanks for the info! I'll try it out.

**Comment by hngenc** [comment]
Closing this for now, but feel free to re-open if you have any questions about `resadd`
