### ISSUE TITLE
Errors in build Verilator.

### ISSUE THREAD

**Issue by Heresyrac** [ucb-bar/gemmini#206]
Hi, I am new to gemmini,
I follow the quick start and get some errors among the "Building Gemmini Hardware and Cycle-Accurate Simulators" step.
Here is the error information.
I want to know what is the problem and how to fix it, thank you.

[info] resolving key references (55373 settings) ...
[info] set current project to chipyardRoot (in build file:/root/chipyard/)
[info] set current project to chipyard (in build file:/root/chipyard/)
[info] compiling 69 Scala sources to /root/chipyard/tools/treadle/target/scala-2.12/classes ...
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:6:8: object ExecutionOptionsManager is not a member of package firrtl
[error] import firrtl.{AnnotationSeq, ExecutionOptionsManager, HasFirrtlOptions}
[error]        ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:32:20: type ComposableOptions is not a member of package firrtl
[error]     extends firrtl.ComposableOptions {
[error]                    ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:34:41: not found: type ExecutionOptionsManager
[error]   def vcdOutputFileName(optionsManager: ExecutionOptionsManager): String = {
[error]                                         ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:73:9: not found: type ExecutionOptionsManager
[error]   self: ExecutionOptionsManager =>
[error]         ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:77:3: not found: value parser
[error]   parser.note("treadle-options")
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:79:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:87:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:95:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:103:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:111:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:119:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:127:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:136:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:144:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:152:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:160:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:168:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:176:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:185:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:206:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:216:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:225:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:254:37: not found: type ExecutionOptionsManager
[error] class TreadleOptionsManager extends ExecutionOptionsManager("engine") with HasTreadleSuite
[error]                                     ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:256:31: not found: type ExecutionOptionsManager
[error] trait HasTreadleSuite extends ExecutionOptionsManager with HasFirrtlOptions with HasTreadleOptions {
[error]                               ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:256:60: not found: type HasFirrtlOptions
[error] trait HasTreadleSuite extends ExecutionOptionsManager with HasFirrtlOptions with HasTreadleOptions {
[error]                                                            ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:246:24: value parser is not a member of treadle.TreadleOptionsManager
[error]     if (optionsManager.parser.parse(args)) {
[error]                        ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:254:61: no arguments allowed for nullary constructor Object: ()Object
[error] class TreadleOptionsManager extends ExecutionOptionsManager("engine") with HasTreadleSuite
[error]                                                             ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:257:9: not found: type ExecutionOptionsManager
[error]   self: ExecutionOptionsManager =>
[error]         ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:260:5: not found: value commonOptions
[error]     commonOptions.toAnnotations ++ firrtlOptions.toAnnotations ++ treadleOptions.toAnnotations
[error]     ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:260:36: not found: value firrtlOptions
[error]     commonOptions.toAnnotations ++ firrtlOptions.toAnnotations ++ treadleOptions.toAnnotations
[error]                                    ^
[warn] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:6:31: Unused import
[warn] import firrtl.{AnnotationSeq, ExecutionOptionsManager, HasFirrtlOptions}
[warn]                               ^
[warn] /root/chipyard/tools/treadle/src/main/scala/treadle/Driver.scala:6:56: Unused import
[warn] import firrtl.{AnnotationSeq, ExecutionOptionsManager, HasFirrtlOptions}
[warn]                                                        ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:8:8: object ExecutionOptionsManager is not a member of package firrtl
[error] import firrtl.{AnnotationSeq, ExecutionOptionsManager}
[error]        ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/TreadleTester.scala:482:7: not found: value commonOptions
[error]       commonOptions = commonOptions.copy(targetDirName = "test_run_dir")
[error]       ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:59:9: not found: type ExecutionOptionsManager
[error]   self: ExecutionOptionsManager =>
[error]         ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:63:3: not found: value parser
[error]   parser.note("firrtl-repl")
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:65:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:74:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:83:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:91:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:100:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:109:3: not found: value parser
[error]   parser
[error]   ^
[warn] /root/chipyard/tools/treadle/src/main/scala/treadle/repl/ReplConfig.scala:8:31: Unused import
[warn] import firrtl.{AnnotationSeq, ExecutionOptionsManager}
[warn]                               ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:5:8: object ExecutionOptionsManager is not a member of package firrtl
[error] import firrtl.ExecutionOptionsManager
[error]        ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:82:33: not found: type ExecutionOptionsManager
[error] class VCDOptionsManager extends ExecutionOptionsManager("vcd") with HasVCDConfig
[error]                                 ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCD.scala:445:17: value parse is not a member of treadle.vcd.VCDOptionsManager
[error]     if (manager.parse(args)) {
[error]                 ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:18:9: not found: type ExecutionOptionsManager
[error]   self: ExecutionOptionsManager =>
[error]         ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:15:20: type ComposableOptions is not a member of package firrtl
[error]     extends firrtl.ComposableOptions {}
[error]                    ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCD.scala:466:15: value parser is not a member of treadle.vcd.VCDOptionsManager
[error]       manager.parser.showUsageAsError()
[error]               ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:22:3: not found: value parser
[error]   parser.note("vcd")
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:24:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:32:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:40:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:48:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:56:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:64:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:73:3: not found: value parser
[error]   parser
[error]   ^
[error] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:82:57: no arguments allowed for nullary constructor Object: ()Object
[error] class VCDOptionsManager extends ExecutionOptionsManager("vcd") with HasVCDConfig
[error]                                                         ^
[warn] /root/chipyard/tools/treadle/src/main/scala/treadle/vcd/VCDConfig.scala:5:15: Unused import
[warn] import firrtl.ExecutionOptionsManager
[warn]               ^
[warn] four warnings found
[error] 55 errors found
[error] (treadle / Compile / compileIncremental) Compilation failed
[error] Total time: 9 s, completed Mar 14, 2022, 6:15:05 PM
/root/chipyard/common.mk:105: recipe for target 'generator_temp' failed
make: *** [generator_temp] Error 1

**Comment by Heresyrac** [comment]
> Can you make sure you ran `source env.sh` before building the Verilator simulator?
> 
> Also, which Chipyard commit, and which Gemmini commit are you on?

Yes, I re-run the env.sh and the error information seems same.
The Gemmini commit is : 
commit 87550581d98210540ac013f96fbcb9150be39df7 (HEAD, tag: v0.6.4, origin/master, origin/HEAD)
Author: Hasan Genc <hngenc@berkeley.edu>
Date:   Mon Mar 7 11:27:05 2022 -0800

    Update version number in Quick Setup instructions

Chipyard commit is : 
commit b5d013190d637e634113cb5179f8c8885df1945a (HEAD -> master, tag: 1.5.0, origin/master, origin/HEAD)
Merge: 45684f1b ba1351c8
Author: alonamid <alonamid@eecs.berkeley.edu>
Date:   Mon Jun 14 21:47:41 2021 -0700

    Merge pull request #773 from ucb-bar/dev

    Chipyard 1.5 Release (Dev -> Master Tracking)

**Comment by hngenc** [comment]
It seems that you're using an older version of Chipyard.

Can you try running [the commands here](https://github.com/ucb-bar/gemmini#installing-chipyard-and-spike), and verify that they all pass? Those commands should set you up with the correct versions of Gemmini, Chipyard, and Spike.

**Comment by Heresyrac** [comment]
@hngenc 
I often encounter network errors in the middle of running these scripts, so I need to run them again many times.  Is it possible that this is the cause of the error？

**Comment by hngenc** [comment]
It's possible. Can you share these network errors?

Also, can you share the full output of your `./scripts/init-submodules-no-riscv-tools.sh` and `./scripts/build-toolchains.sh esp-tools` commands?

**Comment by Heresyrac** [comment]
@hngenc  
The network error are TLS handshake error and unable to access the google-source, for  using china network. 
I have already fixed them by changing the url to ssh form, and setting proxy.
Here are the outputs：

[Outputs.zip](https://github.com/ucb-bar/gemmini/files/8339695/Outputs.zip)


So, maybe I can fix the error by deleting the chipyard again and repeat those steps without network failure?

**Comment by hngenc** [comment]
I don't notice any obvious errors in the outputs you sent me, so I'm not sure why you're getting the error you posted above.

I'm stumped on what could be causing this issue to be honest. I haven't been able to replicate it on my machine.

> So, maybe I can fix the error by deleting the chipyard again and repeat those steps without network failure?

It's worth a try 🤷

**Comment by Heresyrac** [comment]
@hngenc 
Now I success to build verilator, but I still encounter errors in building gemini software.

**Comment by hngenc** [comment]
Your error says

```
riscv64-unknown-elf-gcc: Command not found
```

This implies that you either:

1. Forgot to run `source env.sh`, or
2. Did not successfully run `./scripts/build-toolchains.sh esp-tools`

**Comment by Heresyrac** [comment]
@hngenc Ok I successfully run the test, thank you for the help.

**Comment by hngenc** [comment]
No problem!
