### ISSUE TITLE
Tracing memory access in DRAM and Scratchpad

### ISSUE THREAD

**Issue by kimjungwow** [ucb-bar/gemmini#214]
Hello 😁

Sorry for bothering you again with new issue, but I open this issue because I think this issue and my previous issue (#212) are orthogonal.

I want to trace memory access in DRAM and Scratchpad. The example results I want to get are as follows.
```
Cycle,Addr,R/W,...
32,0x1002fd00,Write
36,0x1003ed00,Write
...
33300,0x2df3e00,Read
33308,0x2df4000,Read
```

1. Is spike not proper for trace memory access in DRAM because Spike does not support realistic DRAM? I already heard that "Spike doesn't accurately model DRAM performance.", but I wonder this kind of tracing also requires accurate DRAM performance modeling.
2. Is spike proper for trace memory access in Scratchpad? I wonder there is an relationship between realistic DRAM and realistic(?) Scratchpad.
3. To trace memory access, should I use printf for all mvin and mvout operations? Or, is there more elegant way to trace memory access?

Thank you!

**Comment by kimjungwow** [comment]
An issue was created before I finished writing by mistake. Now I have filled out all the questions.

**Comment by hngenc** [comment]
Spike should be sufficient for that kind of memory trace.

Try uncommenting this line and rebuilding Spike:

https://github.com/ucb-bar/esp-isa-sim/blob/master/gemmini/gemmini.h#L19

We use that for debugging purposes, but it should also tell you exactly which DRAM and Scratchpad addresses are read from or written to.

**Comment by kimjungwow** [comment]
Thank you Hasan! 👍 It is exactly what I looked for.
