### ISSUE TITLE
Gemmini reduce hardware resource usage

### ISSUE THREAD

**Issue by weihsi** [ucb-bar/gemmini#215]
Hi, I want to reduce LUT and register used by Gemmini, is there any efficient way like adjust GemminiConfig to reduce LUT&Register uses?
Thanks!

**Comment by hngenc** [comment]
You can try copying some of the options from the `leanConfig`, which gets rids of some little-used features to save area:

https://github.com/ucb-bar/gemmini/blob/master/src/main/scala/gemmini/Configs.scala#L239

You can also set these to `false` if you don't want training features, max pooling, or non-linear activation functions (like ReLU) respectively:

https://github.com/ucb-bar/gemmini/blob/master/src/main/scala/gemmini/Configs.scala#L49-L51

Finally, if you just want performance numbers from Gemmini, but you don't care about the functional correctness of your results, you can use the `dummyConfig`:

https://github.com/ucb-bar/gemmini/blob/master/src/main/scala/gemmini/Configs.scala#L167

The `dummyConfig` gets rid of all the mac units and SRAMs, but preserves the cycle-accurate timing of the accelerator.
