### ISSUE TITLE
Cannot run "./scripts/build-toolchains.sh esp-tools"

### ISSUE THREAD

**Issue by Teut0nic** [ucb-bar/gemmini#233]
Hey everyone,

I'm getting some errors while trying to build the toolchains:
![image](https://user-images.githubusercontent.com/78013962/182512505-9583ef5e-9975-4c30-8ad4-7419a34f121a.png)

1. When running the command as shown on in the instructions, I get:

build-toolchains.sh: obsolete make version; need GNU make 4.x or later

So I've been using 'MAKE=/usr/local/bin/make ./scripts/build-toolchains.sh esp-tools' because I think I have an obsolete version of make somewhere, so this gets around that and uses the latest version i've installed.  

2. After running the command above, I get this:
![image](https://user-images.githubusercontent.com/78013962/182512448-a89cacb6-6fcf-4bd4-913c-e15561fde4f8.png)

I'm not sure if I'm missing any dependencies or what I should do next.  I've been stuck on this for a couple days; any help is very appreciated!

**Comment by hngenc** [comment]
Yeah, I've run into the `make` issue myself. The scripts don't always look for `make` where you would expect them to look, unfortunately. Your solution sounds fine to me.

As for the second issue, I'm not sure what that could be. You might want to post about it on the Chipyard mailing list. Can you also try posting the full output of the command in a Gist file, and sharing it in this thread?
