### ISSUE TITLE
Error running build-verilator.sh and run_verilator.sh

### ISSUE THREAD

**Issue by zhongwujie** [ucb-bar/gemmini#239]
My os environment is ubuntu 20.04.
I have followed the instructions and built the toolchain successfully.
```
git clone https://github.com/ucb-bar/chipyard.git
cd chipyard
git checkout 117624d8eea27bafd613eec09e9b9b3e31239e08
./scripts/init-submodules-no-riscv-tools.sh
./scripts/build-toolchains.sh esp-tools

source env.sh

cd generators/gemmini
git fetch && git checkout v0.6.4
git submodule update

cd -
cd toolchains/esp-tools/riscv-isa-sim/build
git fetch && git checkout 090e82c473fd28b4eb2011ffcd771ead6076faab
make && make install
```
However, when I run build-verilator.sh, I get the following errors.
![build-verilator](https://user-images.githubusercontent.com/54237860/186572811-55dbbcf9-df28-4baf-a85a-b21f1960f6c1.png)

When I run run_verilator.sh, it shows that there is no such a config file.
![run-verilator](https://user-images.githubusercontent.com/54237860/186572845-bc2338cf-aa08-4edb-aadc-ee1dd301c94d.png)

**Comment by zhongwujie** [comment]
I wonder if the ubuntu version matters. My ubuntu version is 20.04 while the chipyard document suggests 16.04 and 18.04.

**Comment by hngenc** [comment]
Hmm, usually `Error 137` is caused by an out-of-memory error. Can you try re-running on a machine with more RAM?

**Comment by zhongwujie** [comment]
Thanks. After I set the virtual machine RAM to 8G, it compiled successfully.
