### ISSUE TITLE
Is there a tutorial for fpga here?

### ISSUE THREAD

**Issue by linuxlonelyeagle** [ucb-bar/gemmini#264]
I want to run gemmini on fpga.Is there a tutorial for fpga here?Thanks!

**Comment by gnodipac886** [comment]
@linuxlonelyeagle you can checkout this repo here :)
https://github.com/eugene-tarassov/vivado-risc-v

**Comment by linuxlonelyeagle** [comment]
> @linuxlonelyeagle you can checkout this repo here :) https://github.com/eugene-tarassov/vivado-risc-v

Thanks!

**Comment by hngenc** [comment]
We haven't yet attempted to run Gemmini on a standalone FPGA, although I know some people have managed to do so. But it's not a workflow that we officially support.

However, I believe that more recent versions of Firesim have experimental support for on-premise FPGAs. So you might be able to run Gemmini workloads on your personal FPGAs through Firesim.

**Comment by linuxlonelyeagle** [comment]
> We haven't yet attempted to run Gemmini on a standalone FPGA, although I know some people have managed to do so. But it's not a workflow that we officially support.
> 
> However, I believe that more recent versions of Firesim have experimental support for on-premise FPGAs. So you might be able to run Gemmini workloads on your personal FPGAs through Firesim.

Thanks!
