### ISSUE TITLE
Configure private_stride/mainmemory_stride

### ISSUE THREAD

**Issue by RerikOp** [ucb-bar/gemmini#281]
In the doc it says that both of those strides can be set in the config_mvin. However, I can't see how to differentiate between those two as there seems to be not flag or register for that. Am I missing something?

**Comment by hngenc** [comment]
The private-memory stride (or "scratchpad stride") is set by `rs1[31:16]` in `config_mvin`. The README has been updated to reflect that in commit `4070e2c9dcb16d24445ceabec9e5b4a7215e5ba7`
