### ISSUE TITLE
Error with spike and conv_dw

### ISSUE THREAD

**Issue by Nerotos** [ucb-bar/gemmini#285]
Hello, when I try to run the conv_dw example on Spike, it fails as the results between CPU and Gemmini version don't match. However, if I run the example with Verilator, they match and I get the expected results.
Is there a way to rebuild my Gemmini extension of spike? It seems like something is going wrong with the version I have installed.

**Comment by hngenc** [comment]
Can you try this on the latest version of Gemmini (`v0.7.1`) which was just released? I wasn't able to replicate this issue on that release

**Comment by Nerotos** [comment]
Running fine with the new version. Thank you!
