### ISSUE TITLE
running MeshWithDelays module independently failed

### ISSUE THREAD

**Issue by xiaolingyi** [ucb-bar/gemmini#30]
When I run MeshWithDelays module in the bootcamp environment,I get this error:

**cmd14.sc:166: inferred type arguments [U] do not conform to class TagQueue's type parameter bounds [U <: Helper.this.TagQueueTag with chisel3.Data]
  val tag_queue = Module(new TagQueue(tagqlen:Int, tagType: U)) // TODO understand the actual required size better
                         ^cmd14.sc:166: type mismatch;
 found   : U(in class MeshWithDelays)
 required: U(in class TagQueue)
  val tag_queue = Module(new TagQueue(tagqlen:Int, tagType: U)) // TODO understand the actual required size better
                                                          ^Compilation Failed**

And below is corresponding code:
1.TagQueue

trait TagQueueTag {
  def make_this_garbage(dummy: Int = 0): Unit
}

class **TagQueue[U <: TagQueueTag with Data](entries: Int, t: U)** extends Module {
........
}
2.MeshWithDelays
class MeshWithDelays[T <: Data: Arithmetic, U <: TagQueueTag with Data]
  (inputType: T, val outputType: T, accType: T,
   **_tagType: U_**, df: Dataflow.Value, pe_latency: Int,
   tileRows: Int, tileColumns: Int, meshRows: Int, meshColumns: Int,
   leftBanks: Int, upBanks: Int, outBanks: Int = 1)
  extends Module {
....
  **val tag_queue = Module(new TagQueue(tagqlen:Int, tagType: U)) // TODO understand the actual required size better**

....}
I see some issue says that it is a release problem. and some says I need to explicit define the type .I did the second solution,but don't work.So can somebody help me?I am so confused.I seems that the two type did match each other.

**Comment by hngenc** [comment]
What do you mean by running in the "bootcamp environment"?
