### ISSUE TITLE
couldn't find extension 'gemmini' in shared library 'libcustomext.so'

### ISSUE THREAD

**Issue by sy243293056** [ucb-bar/gemmini#308]
Hello,
I am trying to build gemmini environment following readme.md , but it returns couldn't find extension 'gemmini' in shared library 'libcustomext.so' when i run spike
![2023-07-13 10-54-41屏幕截图](https://github.com/ucb-bar/gemmini/assets/80453085/0b28b7d1-bd3d-4728-8dc8-d919a39c4b02)

**Comment by zhao-denghui** [comment]
hello, i have the same trouble, can you tell me how you solved this question?

**Comment by suhwanhong999** [comment]
I have this issue also. Any updates?
