### ISSUE TITLE
The float32 configuration fails to pass even the simplest test in Verilator

### ISSUE THREAD

**Issue by chguo1995** [ucb-bar/gemmini#341]
I attempted to use the 8*8 float32 configuration as follows:

```
val trainingConfig = defaultFpConfig.copy(
  inputType = Float(expWidth = 8, sigWidth = 24),
  accType = Float(expWidth = 8, sigWidth = 24),

  meshRows = 8,
  meshColumns = 8,
  
  dataflow = Dataflow.WS,

  has_training_convs = true,
  has_max_pool =  false,

  sp_capacity = CapacityInKilobytes(512),
  acc_capacity = CapacityInKilobytes(256),
)
```

However, it fails to pass the _Verilator_ simulation, even for a simple **mvin_mvout.c** test, which gets stuck.

Additionally, in **configsFP.scala**, _spad_read_delay_ was set to **1**. I attempted to change _spad_read_delay_ to **4** (to align with the int8 configuration), which allowed it to pass the **mvin_mvout.c** test and also all the _DIM*DIM_ computations. However, when executing computations related to **tile_matmul.c** or **tile_conv.c**(i.e., involving a series of instructions related to _loop_matmul_ws_ and _loop_conv_ws_), it fails to produce correct results. 

Tested versions include: **v0.7.0, v0.7.1, v0.7.2, and the development version.**

Could you tell me if there is anything that I have overlooked? @hngenc @jerryz123 @AmeerHajAli

**Comment by 1024GeBug** [comment]
Hello, I would like to ask a question. Does Gemmini support the classic FP32 format, which consists of 1 sign bit, 8 exponent bits, and 23 mantissa bits, or does it only support 8 exponent bits and 24 mantissa bits? I have encountered a similar issue when building Gemmini. I would greatly appreciate any help you can provide.

**Comment by 1024GeBug** [comment]
Thank you very much !!!!!!!

**Comment by hansa31** [comment]
Hi! How did you manage to get correct results for tile_matmul.c?
