### ISSUE TITLE
Changing the value of scratchpad does not change the cycles run by workloads. Why is this?

### ISSUE THREAD

**Issue by ArchRookie** [ucb-bar/gemmini#342]
I changed the scratchpad value many times from 64 to 128 to 256, but the cycles run by the simulated workloads will not change. Why is this? Can you solve my doubts? I will be very grateful.

**Comment by hngenc** [comment]
In `gemmini.h`, tiling factors will be calculated for your workloads. For example, `tiled_matmul_auto` calculates tiling factors for matrix multiplications. You should check what your tiling factors are with different sizes for your scratchpad and accumulator. If they are the same, then your performance won't change, because `tiled_matmul_auto` will utilize the same scratchpad capacity even with different scratchpad sizes.

**Comment by ArchRookie** [comment]
Can you explain it in more detail? Really grateful!

**Comment by ArchRookie** [comment]
> In `gemmini.h`, tiling factors will be calculated for your workloads. For example, `tiled_matmul_auto` calculates tiling factors for matrix multiplications. You should check what your tiling factors are with different sizes for your scratchpad and accumulator. If they are the same, then your performance won't change, because `tiled_matmul_auto` will utilize the same scratchpad capacity even with different scratchpad sizes.

Can you explain it in more detail? Really grateful!

**Comment by hngenc** [comment]
> Can you explain it in more detail?

Basically, you want to print out [these tiling factors.](https://github.com/ucb-bar/gemmini-rocc-tests/blob/dev/include/gemmini.h#L1310-L1327)

They determine how many rows of your scratchpad/accumulator SRAMs will be used in each tile of the tiled matrix multiplications.

**Comment by ArchRookie** [comment]
Thank you very much!

> > Can you explain it in more detail?
> 
> Basically, you want to print out [these tiling factors.](https://github.com/ucb-bar/gemmini-rocc-tests/blob/dev/include/gemmini.h#L1310-L1327)
> 
> They determine how many rows of your scratchpad/accumulator SRAMs will be used in each tile of the tiled matrix multiplications.
