### ISSUE TITLE
About the mvout instruction

### ISSUE THREAD

**Issue by 1024GeBug** [ucb-bar/gemmini#350]
I would like to ask whether cachemiss will occur in the mvout instruction? If a cache miss occurs, will the data be cached in L2 first and then written back to the memory? Or does this not happen at all? I would be grateful if you could help me.

**Comment by ArchRookie** [comment]
In addition, I would like to ask whether the config_load command will also affect mvin? thank you for your answer！

**Comment by ArchRookie** [comment]
@growly @zhemao @jwright6323 @jackbackrack
