### ISSUE TITLE
build-setup.sh riscv-tools taking too long to compile

### ISSUE THREAD

**Issue by svs11** [ucb-bar/gemmini#367]
Hi, I am trying to use Gemmini and set up the environment for the accelerator. The setup is stuck at the step "./build-setup.sh riscv-tools". It has been running in the background for more than 48 hours, executing "ctags -R --exclude=@.ctagsignore --links=no". Is it normal for this script to take that long?

<img width="1606" alt="image" src="https://github.com/user-attachments/assets/f9b19f19-b5ee-4945-89f7-2e275c1a8a14">

<img width="1595" alt="image" src="https://github.com/user-attachments/assets/c0bbb6e2-b6fa-40af-8f09-278d8e43b4c4">

**Comment by svs11** [comment]
got it fixed had issue with the system.

**Comment by linbaiwpi** [comment]
may I have the Chipyard and Gemmini as well as Verilator and Chisel version of your configuration? I cannot build Gemmini sucessfully.

> got it fixed had issue with the system.

**Comment by svs11** [comment]
hi , my chipyard version:  1.9.1, gemmini :  v0.7.1, Verilator : 4.226 and SBT Versions: sbt version in this project: 1.3.13
sbt script version: 1.8.2. If you are facing the same problem then remove the tags directory and re-run , if fails again then try to remove the whole directory and build it again.
