### ISSUE TITLE
Fix for deprecated Tiler?

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/gemmini#50]
The following code snippet fails with a divide by 0 error when having `meshRows/Columns` < 8. 

https://github.com/ucb-bar/gemmini/blob/4907ba3a291dac3085f840a117e4bfd248bae8a2/src/main/scala/gemmini/GemminiConfigs.scala#L136

Can be bypassed by the following:
```
val TILE_IDX                    = (BigInt(MNK_BYTES) * 8) / DIM
```

This seems to be used just in the `Tiler*` modules which seems to be unused (the `TilerController` is commented out in the `Controller.scala` file). 

I'll leave the fix here just in case the `Tiler*` code might be deleted.

**Comment by hngenc** [comment]
Closed by #64 

Thanks, @abejgonzalez !
